ALTER TYPE "RestaurantOrderStatus" ADD VALUE IF NOT EXISTS 'PENDING_PAYMENT' BEFORE 'CONFIRMED';

ALTER TABLE "RestaurantOrder"
ADD COLUMN "platformCommission" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN "restaurantSettlement" DECIMAL(10,2) NOT NULL DEFAULT 0;

ALTER TABLE "Payment"
ADD COLUMN "chargedAmount" DECIMAL(10,2),
ADD COLUMN "providerFee" DECIMAL(10,2);
