ALTER TABLE "Restaurant"
ADD COLUMN "openingTime" TEXT NOT NULL DEFAULT '09:00',
ADD COLUMN "closingTime" TEXT NOT NULL DEFAULT '22:00',
ADD COLUMN "operatingDays" INTEGER[] NOT NULL DEFAULT ARRAY[1, 2, 3, 4, 5]::INTEGER[],
ADD COLUMN "timezone" TEXT NOT NULL DEFAULT 'Africa/Lagos';
